// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "22909627-6f43-48f6-ad1b-5e7382194241");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1665437513);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1665437549);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{dd50b429-1e32-4773-a948-bd3e4cc26cd6}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1665437509);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 128);
user_pref("browser.newtabpage.activity-stream.impressionId", "{6058e35f-e0ae-4615-8b1a-31aa7b287af8}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1665437510);
user_pref("browser.search.region", "US");
user_pref("browser.search.separatePrivateDefault.urlbarResult.enabled", false);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20221007233509");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1665437550");
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.homepage", "https://technopig100.github.io/Home/|https://www.mozilla.org/en-US/privacy/firefox/");
user_pref("browser.startup.homepage_override.buildID", "20221007233509");
user_pref("browser.startup.homepage_override.mstone", "105.0.3");
user_pref("browser.startup.lastColdStartupCheck", 1665437549);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "offline");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1665437511251");
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "105.0.3");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "US");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "f9404d1f9c0645d99d4fd6181e9bbbd1");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20221007233509");
user_pref("extensions.lastAppVersion", "105.0.3");
user_pref("extensions.lastPlatformVersion", "105.0.3");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"4ee8f111-39d9-410e-bec2-74d64ab46e3f\",\"pictureinpicture@mozilla.org\":\"95978692-9e05-4dfd-875e-5419dad1d83c\",\"screenshots@mozilla.org\":\"a6bb0120-9008-4be7-bebe-8fd5eee6fc85\",\"webcompat-reporter@mozilla.org\":\"fd48b300-3c0c-4119-89aa-2dc8b3a81b07\",\"webcompat@mozilla.org\":\"62e11741-2f7e-4659-b09d-1c7ed687d0fe\",\"default-theme@mozilla.org\":\"cc7811c5-3d6e-4af6-aef5-a4bfa4a09c6c\",\"addons-search-detection@mozilla.com\":\"32f16cbd-643b-4f27-95db-e51a719e8b5f\",\"google@search.mozilla.org\":\"91873112-1a5b-49d3-a3f1-19b338db4dbd\",\"amazondotcom@search.mozilla.org\":\"4bca111f-11dc-4e70-bb61-f53eaaab1e73\",\"wikipedia@search.mozilla.org\":\"897014d8-259e-4f57-b700-ace412ec08c4\",\"bing@search.mozilla.org\":\"46353f44-fc50-4997-85ff-c16d0a072a14\",\"ddg@search.mozilla.org\":\"a5d13d09-91dd-4750-8703-01bccd627d72\",\"ebay@search.mozilla.org\":\"1250f435-b43c-4914-a74d-248c33c97a2c\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1665437511);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("gfx.blacklist.webrender", 4);
user_pref("gfx.blacklist.webrender.failureid", "FEATURE_FAILURE_OPENGL_LESS_THAN_3");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("nimbus.syncdatastore.tcpByDefault", "{\"slug\":\"tcp-rollout-phase-iii-tcp-on-by-default-for-95-existing-release-profiles\",\"branch\":{\"slug\":\"control\",\"ratio\":1,\"feature\":{\"value\":null,\"enabled\":true,\"featureId\":\"tcpByDefault\"},\"features\":null},\"active\":true,\"enrollmentId\":\"fb534453-c0c3-4e6e-b19e-71399c6a1551\",\"experimentType\":\"nimbus\",\"source\":\"rs-loader\",\"userFacingName\":\"TCP rollout, Phase III (TCP on by default for 95% EXISTING Release profiles)\",\"userFacingDescription\":\"\\\"By default\\\" rollout: Gradually turning on Total Cookie Protection in standard browsing by default for EXISTING user profiles\",\"lastSeen\":\"2022-10-10T21:31:51.541Z\",\"featureIds\":[\"tcpByDefault\"]}");
user_pref("nimbus.syncdatastore.tcpByDefault.enabled", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pref.browser.homepage.disable_button.current_page", false);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "8aa397c9-d782-47ba-b571-85bf4b48cfd9");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.engine.addresses.available", true);
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("toolkit.startup.last_success", 1665437548);
user_pref("toolkit.telemetry.cachedClientID", "62a6cee9-e639-452d-9001-f8e016e7b9e2");
user_pref("toolkit.telemetry.previousBuildID", "20221007233509");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
